
######### This was succesfully used to create both Mistral (8B) and LLAMA3 (8B) models


# Use an official Python runtime as the base image
FROM python:3.9-slim

# Install FFMPEG
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq install --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set the command to run when the container starts
CMD [ "python", "app.py" ]
